service: s3bucket

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  hello:
    handler: handler.hello

    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

    environment:
      PORT: 5000
